apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  ports:
    - name: "26657"
      port: 26657
      targetPort: 26657
    - name: "26656"
      port: 26656
      targetPort: 26656
    - name: "6060"
      port: 6060
      targetPort: 6060
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "1317"
      port: 1317
      targetPort: 1317
  selector:
    io.kompose.service: node
status:
  loadBalancer: {}
